# Generated by Django 4.2.9 on 2024-03-05 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_like_created_at_like_is_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='is_liked',
        ),
    ]
